Order functionality applied
QbaSekowski/spring-book-app pull request #12
Opened 2024-04-04 06:51 UTC by QbaSekowski

2024-04-05 20:05 UTC, nowickimj requested changes

2024-04-05 20:05 UTC, nowickimj commented on src/main/java/mate/academy/springbookapp/service/order/impl/OrderServiceImpl.java
> +        }
1. Avoid using `null` when possible.
2. Think of how should your application behave when user tries to access someone else's resources. I think that you should either return 404 (more secure - you're not telling anyone that resource exists, but may be misleading for debugging) or 403 (more explicit).

2024-04-05 20:05 UTC, nowickimj commented on src/main/java/mate/academy/springbookapp/service/order/impl/OrderServiceImpl.java
> +    public OrderDto placeOrder(User user, PlaceOrderRequestDto requestDto) {
How about cleaning up this method a bit? First - prepare data, then create new `Order` object and set values. Additionally, you might want to try out Lombok's `@Builder`.

2024-04-05 20:05 UTC, nowickimj commented on src/main/java/mate/academy/springbookapp/dto/order/UpdateStatusRequestDto.java
> +        String status) {
How about using enum here?

2024-04-07 17:53 UTC, okuzan approved these changes
A few suggestions:
Don't use @ Data on JPA entities, it has [side effects](https://thorben-janssen.com/lombok-hibernate-how-to-avoid-common-pitfalls/#avoid-data)
Don't use short uninformative variables' names in stream chains
Don't forget to leave the last line empty (regarding your .yaml scripts)
Extract /api to project wide prefix - `server.servlet.context-path`
@ Where is deprecated, replace with @ SQLRestriction

2024-04-08 08:07 UTC, merged